### ISSUE TITLE
Can't step a zero degree polynomial

### ISSUE THREAD

**Issue by marianomds** [python-control/python-control#165]
When running:
```
import control as ctrl
G = ctrl.tf([1],[1])
(y, t) = ctrl.step(G)
```

I get this error (I get the same in python 2.7 and 3.5):

Traceback (most recent call last):
  File "./prueba.py", line 10, in <module>
    (y, t) = ctrl.step(G)
  File "/usr/local/lib/python3.5/dist-packages/control/matlab.py", line 1328, in step
    transpose = True, **keywords)
  File "/usr/local/lib/python3.5/dist-packages/control/timeresp.py", line 483, in step_response
    sys = _get_ss_simo(sys, input, output)
  File "/usr/local/lib/python3.5/dist-packages/control/timeresp.py", line 409, in _get_ss_simo
    sys_ss = _convertToStateSpace(sys)
  File "/usr/local/lib/python3.5/dist-packages/control/statesp.py", line 656, in _convertToStateSpace
    ssout = td04ad('R',sys.inputs, sys.outputs, index, den, num,tol=0.0)
  File "/usr/local/lib/python3.5/dist-packages/slycot/transform.py", line 423, in td04ad
    out = _wrapper.td04ad_r(m,p,index,dcoeff,ucoeff,n,tol,ldwork)
ValueError: failed to create intent(cache|hide)|optional array-- must have defined dimensions but got (1,0,)

**Comment by murrayrm** [comment]
Confirmed that this is a bug in the latest versions of the code (including several fixes).  The time response functions are not set up to handle static systems properly.
