### ISSUE TITLE
Slycot installation failing in Travis CI

### ISSUE THREAD

**Issue by murrayrm** [python-control/python-control#168]
In the latest builds on `python-control`, the `slycot` installation is failing and so unit tests are not being run across the `slycot` version of the library.  It appears that what is happening is that the conda builds for `slycot` are out of date and so don't install properly under the Travis CI build script.

**Comment by murrayrm** [comment]
Error message from PR #169 when executing `python -c "import slycot"`:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/slycot/__init__.py", line 16, in <module>
    from .analysis import ab01nd,ab05md,ab05nd,ab07nd,ab08nd, \
  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/slycot/analysis.py", line 21, in <module>
    from . import _wrapper
ImportError: libgfortran.so.3: cannot open shared object file: No such file or directory
```
